# Generated by Django 2.2.5 on 2020-04-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='uname',
        ),
        migrations.AddField(
            model_name='live_track_record',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='face_app.uploadImage'),
        ),
        migrations.AddField(
            model_name='users',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='face_app.uploadImage'),
        ),
    ]
