# Generated by Django 2.2.5 on 2020-04-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0002_auto_20200426_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='passwd',
            new_name='address',
        ),
    ]
