# Generated by Django 2.2.5 on 2020-04-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0003_auto_20200426_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='aadharno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
