# Generated by Django 2.2.5 on 2020-05-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0007_auto_20200428_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_address',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
