# Generated by Django 2.2.5 on 2020-05-01 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0008_ip_address_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ip_status_reprot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipadd', models.CharField(max_length=50, null=True)),
                ('in_time', models.CharField(max_length=50, null=True)),
                ('out_time', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('passwd', models.CharField(max_length=50, null=True)),
                ('phoneno', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users_reprot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.CharField(max_length=50, null=True)),
                ('out_time', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='face_app.users')),
            ],
        ),
    ]
