# Generated by Django 2.2.5 on 2020-05-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0009_ip_status_reprot_users_users_reprot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ip_status_reprot',
            new_name='ip_status_report',
        ),
        migrations.RenameModel(
            old_name='users_reprot',
            new_name='users_report',
        ),
    ]
