# Generated by Django 2.2.5 on 2020-05-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0010_auto_20200502_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='creat_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
