# Generated by Django 2.2.5 on 2020-05-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0011_users_creat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
