# Generated by Django 2.2.5 on 2020-05-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0012_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_report',
            name='in_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='users_report',
            name='out_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
