# Generated by Django 2.2.5 on 2020-05-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0013_auto_20200503_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_report',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
