# Generated by Django 2.2.5 on 2020-05-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0016_auto_20200503_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_report',
            name='status',
        ),
    ]
