# Generated by Django 2.2.5 on 2020-05-03 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0017_remove_users_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_report',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
