# Generated by Django 2.2.5 on 2020-05-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0018_auto_20200503_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_status_report',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users_report',
            name='in_time',
            field=models.DateTimeField(null=True),
        ),
    ]
